openapi: 3.0.1
info:
  title: Shop API
  version: v1
servers:
  - url: http://localhost:3000
paths:
  /api/v1/products:
    get:
      summary: Danh sách sản phẩm
      responses:
        '200':
          description: OK
  /api/v1/orders:
    post:
      summary: Tạo đơn hàng
      responses:
        '201':
          description: Created
