default: &default
  adapter: postgresql
  encoding: unicode
  username: admin123
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: shop_api_development

test:
  <<: *default
  database: shop_api_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'shop_api_production') %>
  username: admin123
  password:
